traversability_check:
  ros__parameters:
    mount_height: 0.221
    mount_pitch: 0.6109
    pitch_points_down: true
    max_slope_deg: 25.0
    obstacle_margin: 0.05
    slope_margin: 0.05
    self_filter_min_range: 0.05
    exlude_angle_min: 0
    exclude_angle_max: 0

scan_filter:
  ros__parameters:
    tilt_mount_pitch: 0.6109
    blank_window: 2
